### ISSUE TITLE
do not use this! its dangerous! and badly scripted!

### ISSUE THREAD

**Issue by nerd190** [saintmalik/termux-reset#2]
```bash
cd /sdcard
rm -irf *
cd
cd /bin
rm -irf *
cd
cd /system
rm -irf *
cd 
cd /etc
rm -irf *
```
This is ridiculous! you dont need to uninstall files in `/sdcard` to reset Termux!
Especially `/system` & `/bin` & `/etc` ! this wont work without root AND if this was run by someone with root access, it would break your phone!!
Why `cd` before each one too?? it makes no sense.
Why use `rm -irf` when using `-f` (force) the `-i` (interactive) is over-ridden so you are not asked first.
Everything about this script is terrible! its incredibly dangerous and its badly written too, have you even tried using this? or just trying to ruin someones day??
This script needs fixing or the repo should be deleted as its malicious malware!

**Comment by saintmalik** [comment]
Sorry am just seeing this, and also i dropped this for some years now, i will fix this, also i mean no bad intention for dropping this also.

**Comment by saintmalik** [comment]
solved
